spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/buyer?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /
  port: 8105
logging:
  pattern:
#    console: "%d - %msg%n"
